name: Snyk Code Scan (Supabase)

on:
  push:
    branches: [main]
  pull_request:

permissions:
  security-events: write  # Allow code scanning uploads

jobs:
  snyk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Scan login function
        run: snyk code test supabase/functions/login.ts --sarif > login.sarif || true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Scan login_snyk_vul_test function
        run: snyk code test supabase/functions/login_snyk_vul_test.ts --sarif > login_snyk_vul_test.sarif || true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Combine SARIF files safely
        shell: bash
        run: |
          if [[ -s login.sarif && -s login_snyk_vul_test.sarif ]]; then
            jq -s '.[0].runs += .[1].runs | .[0]' login.sarif login_snyk_vul_test.sarif > snyk-functions.sarif
          elif [[ -s login.sarif ]]; then
            cp login.sarif snyk-functions.sarif
          elif [[ -s login_snyk_vul_test.sarif ]]; then
            cp login_snyk_vul_test.sarif snyk-functions.sarif
          else
            echo '{"version":"2.1.0","runs":[]}' > snyk-functions.sarif
          fi

      - name: Lint Supabase SQL Migrations
        run: |
          pip install --user sqlfluff
          sqlfluff lint supabase/migrations --dialect postgres || true

      - name: Upload SARIF to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk-functions.sarif
