name: Snyk Code Scan (Supabase)

on:
  push:
    branches: [main]
  pull_request:

jobs:
  snyk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Scan Supabase functions
        run: snyk code test supabase/functions --sarif > snyk-functions.sarif || true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Lint Supabase SQL Migrations
        run: |
          pip install --user sqlfluff
          sqlfluff lint supabase/migrations --dialect postgres || true

      - name: Upload SARIF to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk-functions.sarif
